added new MD file for mapping tutorials
ironhacks/Tutorials-COVID-19 pull request #33
Opened 2023-04-03 18:40 UTC by twinblade02

requesting review

2023-04-03 20:02 UTC, harshpavuluri requested changes
Looks good for the most part. Just that 1 change. Also do a spell check real quick as well as I did see some spelling errors on that 1 line I commented

2023-04-03 20:02 UTC, harshpavuluri commented on tutorials-fall-2022/python/tutorial-7-geoMaps.md
> +The code above is simply preprocessing the files you need to get them to a point where it is possbile to visualize data with Folium quickly.
"The code above is simply preprocessing the files. You will need to additionally process them in a way that you see fit to visualize them with Folium, which we will show you how to use later on."

Editing for clarity here

2023-04-04 02:13 UTC, twinblade02 reviewed
Will do. I'll check the grammar.

2023-04-05 17:49 UTC, harshpavuluri approved these changes
LGTM

2023-04-05 17:49 UTC, merged